apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: baas-app-multi-cluster
 namespace: argocd
spec:
 generators:
 - list:
     elements:
     - cluster: kind-kind-jared
       url: https://kubernetes.default.svc
       values:
         path: appDeployDemo/demo1/dev
     - cluster: kind-dev-cluster
       url: https://192.168.1.139:8443
       values:
         path: appDeployDemo/demo1/prod
 template:
   metadata:
     name: '{{cluster}}-baas'
   spec:
     project: baas-app
     source:
       repoURL: https://github.com/Jared-Xu-Edi/argo-app-deploy.git
       targetRevision: HEAD
       path: appDeployDemo/demo1/dev
     destination:
       server: '{{url}}'
       namespace: baas
     syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true